name: Push to Main Repository Every 5 Minutes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-mirror:
    if: github.repository == 'monogocoro/wiki-work'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repositories: monogocoro/wiki-test
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git remote add mirror https://github.com/monogocoro/wiki-test.git
          git push mirror -f
